# Generated by Django 5.1.3 on 2026-01-18 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('optionA', models.TextField()),
                ('optionB', models.TextField()),
                ('optionC', models.TextField()),
                ('optionD', models.TextField()),
                ('correctOption', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('performance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mcqs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('practical_no', models.PositiveIntegerField(default=0)),
                ('batch', models.CharField(choices=[('A', 'Batch A'), ('B', 'Batch B'), ('C', 'Batch C')], default='A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('quizId', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('isAttempted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='is_verified',
            new_name='otp_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 18, 5, 9, 37, 280989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='college_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roll_no',
            field=models.CharField(default='default_roll_no', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stream',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'otp_code'], name='DSA_otp_user_id_b7857e_idx'),
        ),
    ]
