# Generated by Django 5.1.3 on 2026-01-27 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0002_quiz_studentresult_usersubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 27, 13, 37, 56, 759653, tzinfo=datetime.timezone.utc)),
        ),
    ]
